### ISSUE TITLE
Set some editor defaults

### ISSUE THREAD

**Issue by me2beats** [goblinengine/goblin#3]
The build has a custom theme.
I suggest some other defaults.
for example Idle Parse Delay
![изображение](https://user-images.githubusercontent.com/16458555/172031708-81e3692d-10aa-4ab2-8cd7-e72a4a47336b.png)

Usually I set it to **0.5,** and I don't get why it's 2 sec by default even in Godot4
Gonna ask it in Godot proposals discussions:)

**Comment by filipworksdev** [comment]
I assume is to avoid false positives and not be too annoying to new users. At lower values I think it completes really quickly?

**Comment by filipworksdev** [comment]
I think we should move this one to Dscussions since it would be a few random little settings to change. Feel free to open a thread in Discussions. I personally have already changed a couple myself too already.
